FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN  pip3 install --no-cache-dir -r requirements.txt
COPY webservice ./webservice

WORKDIR /app/webservice
ENV TZ=Asia/Shanghai
ENV PYTHONPATH="/app:$PYTHONPATH"
EXPOSE 5010/tcp
ENTRYPOINT ["gunicorn", "-c", "config.py", "app:app"]