upstream api {
    server app:5005;
}

server {
    listen 5001;
    location / {
        add_header Cache-Control no-store;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;  
    }

    location /api/ {
        proxy_pass http://api/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root  /usr/share/nginx/html;
    }
}